name: Displaying name of the workflow

on:
  push:

jobs:
  display_job_name:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7.0.0
      - name: Display Step name
        run: echo "The name of this workflow is:" ${{ github.workflow }}
      - name: List files
        run: ls -la
      - name: Read files
        run: cat actions-1/README.md