name: Matrix Configuration Workflow
on:
  workflow_dispatch:
  push:

jobs:
  deploy:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, ubuntu-22.0.4]
        images: [hello-world, alpine]
        exclude:
          - images: alpine
            os: windows-latest
        include:
          - images: amd64/alpine
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Echo docker details
        run: docker info
      - name: Run images
        run: docker run ${{ matrix.images }}