name: Matrix Configuration Workflow
on:
  workflow_dispatch:
  push:

jobs:
  deploy:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, ubuntu-22.0.4]
        images: [hellow-world, alpine]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Echo docker details
        run: docker info
      - name: Run images
        run: docker run ${{ matrix.images }}