name: Env Vars and Secrets

on:
  push:

env:
  docker_username: dockerUsername
  docker_password: password

  
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Docker build
        run: docker build -t my-image:latest .
      - name: Docker login
        run: docker login --username=$docker_username --password=$docker_password
      - name: Docker push
        run: docker push my-image:latest
  deploy:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Docker Run
        run: docker run -d -p 80:80 my-image:latest