name: Env Vars and Secrets

on:
  ##push:
  #schedule:
   # - cron: "*/1 * * * *"
  workflow_dispatch:

env:
  docker_username: dockerUsername
  docker_password: password

  
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Docker build
        run: docker build -t my-image:latest .
      - name: Docker login
        run: docker login --username=${{ vars.docker_username }} --password=${{ vars.docker_password }}
      - name: Docker push
        run: docker push my-image:latest
  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: docker
    concurrency:
      group: prod-deploy
      cancel-in-progress: true
    steps:
      - name: Docker Run
        timeout-minutes: 1
        run: | 
             echo docker run -d -p 80:80 my-image:latest
             sleep 600s